
language: swift
osx_image: xcode11.3
os: osx

script: xcodebuild clean build test -project Test-Ci.xcodeproj -scheme "Test-Ci" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.3,name=iPhone X" CODE_SIGN_IDENTIY="" CODE_SIGNING_REQUIRED=NO
